project_name: gti

builds:
  - binary: gti

    main: .
    ldflags:
      - -s -w -X main.version={{.Version}}

    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - solaris
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm

archive:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE

release:
  disable: true
